project:
  type: website
  render:
    - index.qmd
    - about.qmd
    - "src/**/*.qmd"

lang: zh

website:
  title: "Rong's Notes"
  draft-mode: gone
  navbar:
    left:
      - href: index.qmd
        text: 首页
      - href: src/learn/index.qmd
        text: 专题学习
      - href: about.qmd
        text: 关于
  sidebar:
    style: docked
    search: true
    collapse-level: 3
    pinned: true
    contents:
      - href: index.qmd
        text: 首页
      - auto: "src/learn"
      - href: about.qmd
        text: 关于

format:
  html:
    theme:
      - journal
      # - cosmo
      # - quartz
      # - brand
    css: styles.css
    toc: true
    toc-location: right
    toc-title: "目录"
    include-after-body:
      - scripts/proof-collapse.html
      - scripts/math-env-fix.html
    fig-align: center

crossref:
  title-delim: " "
  thm-title: "定理"
  lem-title: "引理"
  cor-title: "推论"
  prp-title: "命题"
  cnj-title: "猜想"
  def-title: "定义"
  exm-title: "例"
  exr-title: "习题"

  fig-title: "图"
  fig-prefix: "图"


# 自动缓存运行结果
execute:
  freeze: auto
