---
title: "测度扩张"
draft: false
aliases:
  - 测度的扩张
author:
  - 荣志炜
tags:
  - 强sigma有限
  - 测度扩张
  - 完全化
date: 2024-03-27 16:00
date-modified: last-modified
order: 5
---

# 引言

正如我们之前提到的，构造一个合适的 $\sigma$-field 是非常难的。同样，在一般的 $\sigma$-field 上构造 measure 也是非常困难的。通常的做法是先在“宽松”的集合系（semi-ring）上建立 measure，然后将其扩张到其 generated $\sigma$-field 上。

# 测度扩张的定义

首先，我们需要严格定义一下测度扩张：

::: {#def-05-measure-extension-1}

## 测度的扩张和扩张的唯一性

假设存在两个集合系 $\mathcal{E}$ 和 $\mathcal{E}'$ 和它们上面的两个测度 $\mu$ 和 $\mu'$，满足 $\mathcal{E}\subset \mathcal{E}'$。如果

$$
\forall A\in\mathcal{E}\implies \mu(E)=\mu'(E),
$$

则称 **$\mu'$ 是 $\mu$ 在 $\mathcal{E}'$ 上的扩张**。
如果任意一个定义在 $\mathcal{E}'$ 上的满足

$$
\forall A\in\mathcal{E}\implies \mu (E)=\tau(E)
$$

的测度 $\tau$ 都会导致 $\tau=\mu'$（在 $\mathcal{E}'$ 上），则称**扩张是唯一的**。

:::
为了能够完成测度扩张的目的，我们似乎可以使用上一小节介绍的 [Caratheodory定理](04-outer-measure.qmd#thm-caratheodory)：即**首先利用 $\mathcal{E}$ 上的测度去构建一个外测度 $\tau$，然后利用该定理将 $\tau$ 限制在 $\mathcal{F}_{\tau}$ 中，不就将测度扩张到一个更大的 $\mathcal{F}_{\tau}$ 中了吗？**

其实未必如此。关键在于，这个过程中我们是先扩大了集合系（从 $\mathcal{E}$ 扩张到了 power set）又缩小了集合系（从 power set 缩小到 $\mathcal{F}_{\tau}$），因此 $\mathcal{F}_{\tau}$ 未必比 $\mathcal{E}$ 范围大。可以看下面的例子：

::: {#exm-05-measure-extension-2}

## Example

假设集合 $X=\{ a,b,c \}$，$\mathcal{E}=\{ \emptyset,\{ a,b \},\{ b,c \},X \}$，并定义上面的一个测度 $\mu$，满足

$$
\mu(\emptyset)=0,\mu(\{ a,b \})=1,\mu(\{ b,c \})=1,\mu(X)=2.
$$

则由 $\mu$ 生成的外测度 $\tau$ 满足

$$
\tau(\emptyset)=0,\tau(X)=\tau(\{ a,c \})=2,\tau(\{ a \})=\tau(\{ b \})=\tau(\{ c \})=\tau(\{ a,b \})=\tau(\{ b,c \})=1.
$$

容易证明：

$$
\mathcal{F}_{\tau}=\{ \emptyset,X \},
$$

其要比 $\mathcal{E}$ 要小。(主要针对 $\{ a,b \}$ 和 $\{ b,c \}$ 来验证即可)

:::
思考上面这个例子，可以发现关键在于 $\mathcal{E}$ 的结构，如果能够对其进行一些限制，则可能实现我们预想中的测度扩张。

首先， 我们需要证明一个引理

::: {#lem-pi-class-extension}

## $\pi$-class 的扩张

设 $\mathcal{T}$ 是一个 $\pi$-class，若 $\sigma(\mathcal{T})$ 上的测度 $\mu,\nu$ 满足下面两个条件：
1. $\forall A\in\mathcal{T}\implies \mu(A)=\nu(A)$;
2. 存在两两不交的 $\{ A_{n}\in\mathcal{T},n=1,2,\dots \}$，使 $\bigcup_{n=1}^{\infty}A_{n}=X$ 且 $\mu(A_{n})<\infty$；

则 $\forall A\in\sigma(\mathcal{T})\implies\mu(A)=\nu(A)$。

:::

::: {.proof}
$\forall B \in\mathcal{T},\mu(B)<\infty$，定义

$$
\mathcal{L}:=\{ A\in\sigma(\mathcal{T})|\mu(A\cap B)=\nu(A\cap B) \}.
$$

现在我们证明 $\mathcal{L}$ 是一个 $\lambda$-class，这需要证明 3 条：

1. $\Omega$ 在其中。
2. $\forall A_{1},A_{2}\in\mathcal{L},A_{1}\subset A_{2}\implies A_{1}\setminus A_{2}\in\mathcal{L}$。
3. $A_{n}\in\mathcal{L},n=1,2,\dots;A_{n}\uparrow\implies \bigcup_{n=1}^{\infty}A_{n}\in\mathcal{L}$。


1是显然的。2的证明如下：

$$
\begin{align}
\mu((A_{1}\setminus A_{2})\cap B)
&=\mu((A_{1}\cap B)\setminus(A_{2}\cap B)) \\
&=\mu(A_{1}\cap B)-\mu(A_{2}\cap B) \\
&=\nu(A_{1}\cap B)-\nu(A_{2}\cap B) \\
&=\nu((A_{1}\setminus A_{2})\cap B)
\end{align}
$$

该步骤中，$\mu(B)<\infty$ 在第二个等号处起到作用。其保证了 $\mu(A_{2}\cap B)<\infty$，这样才能够使得 $\mu(A_{1}\cap B)-\mu(A_{2}\cap B)$ 有意义。

3的证明如下：

$$
\begin{align}
\mu\left( \bigcup_{n=1}^{\infty}A_{n}\cap B \right)
&=\mu\left[ \bigcup_{n=1}^{\infty}(A_{n}\cap B) \right] \\
&=\lim_{ n \to \infty } \mu(A_{n}\cap B) \\
&=\lim_{ n \to \infty } \nu(A_{n}\cap B) \\
&=\nu\left(\bigcup_{n=1}^{\infty}A_{n}\cap B \right)
\end{align}
$$

因此，$\mathcal{L}$ 是一个 $\lambda$ -class。又由引理的条件 1，我们可以知道 $\mathcal{T}\subset \mathcal{L}$，$\mathcal{T}$ 是一个 $\pi$ -class，因此可知 $\mathcal{L}\supset\sigma(\mathcal{T})$，也就是

$$
\forall A\in\sigma(\mathcal{T}),B\in\mathcal{T},\mu(B)<\infty\implies \mu(A\cap B)=\nu(A\cap B).
$$

取得符合条件 2 的 $\{ A_{n} \}$，则 $\forall A\in\sigma(\mathcal{T})$，有

$$
\begin{align}
\mu (A)&=\mu\left( A\cap \bigcup_{n=1}^{\infty}A_{n} \right)\\
&=\sum\limits_{n=1}^{\infty}\mu(A\cap A_{n}) \\
&=\sum\limits_{n=1}^{\infty}\nu(A\cap A_{n}) \\
&=\nu\left( A \cap \bigcup_{n=1}^{\infty}A_{n} \right) \\
&=\nu(A)
\end{align}
$$

其中，最关键的第三行就是利用我们上面得到的等式。
:::

**注意到**，条件 2 (后面我们将其称为 **“强 $\sigma$ 有限”** ) 与$\sigma$有限非常相似，但实际上要比 $\sigma$ 有限更强。$\sigma$ 有限要求

$$
\forall A\in\mathcal{T},\exists \{ A_{n}\in\mathcal{T},n=1,2,\dots \},\mu(A_{n})<\infty\implies \bigcup_{n=1}^{\infty}A_{n}\supset A
$$

和条件 2 主要有两点不同：

1. $X$ 不一定在 $\mathcal{T}$ 中;
2. $\{ A_{n},n=1,2,\dots \}$ 没有要求两两不交。因为 $\mathcal{T}$ 仅限制在 $\pi$-class 上，所以我们无法将其推广至两两不交的情况。

因此，条件 2 蕴含 $\sigma$ 有限，但反之不成立。

::: {.callout-tip title="Help: 证明技巧：$\sigma$-field 满足某种性质"}
要证明一个 $\sigma(\mathcal{E})$ 满足某种条件，一种常用的证明思路是：首先去构造一个满足该条件的集合，然后证明其是一个 $\sigma$-field 并且包含 $\mathcal{E}$，自然其包含 $\sigma(\mathcal{E})$，也就是说 $\sigma(\mathcal{E})$ 中的所有元素都有这个性质。

:::
# 基于半环的扩张（测度扩张定理）

现在我们可以去证明测度扩张定理了，其表明，我们只需要将 $\mathcal{E}$ 限制为 semi-ring，则我们预想中的测度扩张就可以实现。

::: {#thm-measure-extension}

## 测度扩张定理

对于 semi-ring $\mathcal{L}$ 上的 measure $\mu$，存在 $\sigma(\mathcal{L})$ 上的测度 $\tau$ 使得

$$
\forall A\in\mathcal{L}\implies \tau(A)=\mu(A).
$$

如果存在两两不交的 $\{ A_{n}\in\mathcal{L},n=1,2,\dots \}$，使得 $\mu(A_{n})<\infty$ 且 $\bigcup_{n=1}^{\infty}A_n=\Omega$，则使得上式成立的 $\tau$ 唯一。

:::

::: {.proof}
首先，使用 $\tau$ 表示由 $\mu$ 生成的外测度。我们需要依次证明以下 5 个子命题：

**第一， $\forall A\in\mathcal{L}\implies \mu(A)=\tau(A)$。**

$\forall \{ A_{n}\in\mathcal{L},n=1,2,\dots \}$，其满足 $\bigcup_{n=1}^{\infty}A_{n}\supset A$，则有

$$
\begin{align}
\mu(A)&=\mu\left( \bigcup_{n=1}^{\infty}A_{n}\cap A \right) \\
&\leq \sum\limits_{n=1}^{\infty}\mu(A_{n}\cap A) \\
&\leq \sum\limits_{n=1}^{\infty}\mu(A_{n})
\end{align}
$$

这意味着 $\mu(A)\leq \tau(A)$。
反之，取 $B_{1}=A,B_{n}=\emptyset,\forall n\geq 2$，则 $\bigcup_{n=1}^{\infty}B_{n}\supset A$，所以

$$
\mu(A)=\sum\limits_{n=1}^{\infty}B_{n}\geq \tau(A)
$$

因此，$\mu(A)=\tau(A)$。

**第二，$\forall A,D\in\mathcal{L}\implies \tau(D)\geq \tau(D\cap A)+\tau(D\cap A^{c})$。**

由 semi-ring 的定义可以知道，$\exists \{ B_{i}\in\mathcal{L},i=1,\dots,n \}$ 且两两不交，使得 $D\setminus A=\bigcup_{i=1}^{n}B_{i}$。因此，

$$
\begin{align}
\tau(D)&=\mu(D) \\
&=\mu(D\cap A)+\mu(D\cap A^{c}) \\
&=\mu(D\cap A)+\sum\limits_{i=1}^{n}\mu(B_{i}) \\
&=\tau(D\cap A)+\sum\limits_{i=1}^{n}\tau(B_{{i}}) \\
&\geq \tau(D\cap A)+\tau(D\cap A^{c}) \\
\end{align}
$$

**第三，$\mathcal{L}\in\mathcal{F}_{\tau}$。**

为此，我们需要证明 $\forall A\in\mathcal{L},D\in\mathcal{P}(\Omega)$ 有

$$
\tau(D)=\tau(D\cap A)+\tau(D\cap A^{c}).
$$

当 $\tau(D)=\infty$ 时，由外测度的半有限可加性可知结论成立。
现在假设 $\tau(D)<\infty$，由生成外测度的定义（一个下确界），可知 $\forall\epsilon>0$，存在 $\{ B_{n}\in\mathcal{L},n=1,2,\dots \}$ 且 $\bigcup_{n=1}^{\infty}B_{n}\supset D$，有

$$
\begin{align}
\tau(D)+\epsilon&\geq \sum\limits_{n=1}^{\infty}\mu(B_{n}) \\
&=\sum\limits_{n=1}^{\infty}\tau(B_{n}) \\
&\geq \sum\limits_{n=1}^{\infty}\tau(B_{n}\cap A)+
\sum\limits_{n=1}^{\infty}\tau(B_{n}\cap A^{c}) \\
&\geq \tau\left( \bigcup_{n=1}^{\infty}B_{n}\cap A \right)+
\tau\left( \bigcup_{n=1}^{\infty}B_{n}\cap A^{c} \right) \\
&\geq \tau(D\cap A)+\tau(D\cap A^{c})
\end{align}
$$

因为 $\epsilon$ 的任意性，可知 $\tau(D)\geq \tau(D\cap A)+\tau(D\cap A^{c})$。再根据外测度的半可加性可以证明另外一个方向，因此结论得证。

**第四，$\tau$ 是 $\sigma(\mathcal{L})$ 上的测度。**

这是因为 $\mathcal{F}_{\tau}$ 是一个 $\sigma$ -field，则 $\mathcal{F}_{\tau}\supset\sigma(\mathcal{L})$，而 $\tau$ 在 $\mathcal{F}_{\tau}$ 上是一个 measure，则在其子 $\sigma$ -field 上也是一个 measure。

**第五，若补充条件成立，则唯一性成立。**

因为 semi-ring 也是 $\pi$-class，所以可以直接使用引理，得到证明。
:::

实际情况下，我们可能会更常使用该定理的另外一个版本，其使用 $\sigma$ 有限作为条件。

::: {#cor-measure-extension-2}

## 测度扩张定理（$\sigma$ 有限测度）

设 $\mathcal{L}$ 是一个 semi-ring，**$\Omega \in\mathcal{L}$**，$\mu$ 是 $\mathcal{L}$ 上的一个 $\sigma$ 有限测度，则在 $\sigma(\mathcal{L})$ 上存在唯一的测度 $\tau$ 使得

$$
\forall A\in\mathcal{L}\implies \mu(A)=\tau(A).
$$

:::

::: {.proof}
我们只需要证明**强 $\sigma$ 有限条件**成立即可。因为 $\Omega \in\mathcal{L}$，再根据 $\sigma$ 有限的定义，可以知道

$$
\exists \{ A_{n}\in\mathcal{L},n=1,2,\dots \},\mu(A_{n})<\infty\implies \bigcup_{n=1}^{\infty}A_{n}=\Omega.
$$

这里 $\{ A_{n} \}$ 不一定是两两不交的，但是我们可以这样构造

$$
\begin{align}
&B_{1}=A_{1} \\
&B_{2}=A_{2}\setminus B_{1}=\bigcup_{j=1}^{n_{2}}C_{2j}\quad\{ C_{2j} \}\text{两两不交} \\
&\dots\\
&B_{n}=A_{n}\setminus\left( \bigcup_{i=1}^{n=1}B_{i} \right)=
\bigcup_{i=1}^{n-1}\bigcup_{j=1}^{n_{i}}C_{ij}\quad\{ C_{ij} \}\text{两两不交} \\
\dots
\end{align}
$$

两两不交的 $\{ C_{ij} \}$ 的存在是由 semi-ring 的定义所保证的。这样我们就构造了一个 $\{ C_{ij} \}$ 是满足补充条件的。
:::

::: {.callout-note}
尽管**强 $\sigma$ 条件**要比 $\sigma$ 有限性要强，但 semi-ring 的结构保证了可以将非 disjoint 的集合序列构造成 disjoint 的集合序列，并且我们还额外要求了 $\Omega$ 的存在。这就让其和 $\sigma$ 有限性等价了。

:::
因此，这里我们可以有一个小小的引理可以使用：

::: {#lem-sigma-finite}

## $\sigma$ 有限和补充条件之间的关系

设 $\mathcal{L}$ 是一个 semi-ring，如果 $\Omega \in\mathcal{L}$，且 $\mu$ 是 $\mathcal{L}$ 上的 $\sigma$ 有限测度，则上述定理中使用的补充条件（强 $\sigma$ 条件）成立，即存在 disjoint $\{ A_{n}\in\mathcal{L},n=1,2,\dots \}$，$\bigcup_{n=1}^{\infty}A_{n}=\Omega$ 且 $\mu(A_{n})<\infty$。

:::

我们现在知道：测度扩展实际上先从一个 semi-ring 将测度扩展到 $\mathcal{F}_{\tau}$ 上，然后再将其限制到 $\sigma(\mathcal{L})$。现在我们进一步的问题是：**作为 $\sigma(\mathcal{L})$ 的测度 $\tau$ 和作为 $\sigma(\mathcal{F}_{\tau})$ 上的测度 $\tau$，有什么样的区别呢？**

::: {#thm-extension-diff}

## 测度扩张前后的差异

设 $\tau$ 是 semi-ring $\mathcal{L}$ 上测度 $\mu$ 生成的外测度，则

1. $\forall A\in\mathcal{F}_{\tau}\implies \exists B\in\sigma(\mathcal{L}),B\supset A,\tau(A)=\tau(B)$;
2. 若 $\exists \{ A_{n}\in\mathcal{L},n=1,2,\dots \}$ 两两不交,且 $\bigcup_{n=1}^{\infty}A_{n}=\Omega$ 和 $\mu(A_{n})<\infty$ （**强 $\sigma$ 条件**），则有
  $$
  \forall A\in\mathcal{F}_{\tau}\implies\exists B\in\sigma(\mathcal{L}),B\supset A,\tau(B\setminus A)=0
  $$

:::

::: {.proof}
若 $\tau(A)=\infty$，则我们只需要取 $B=\Omega$ 即可。现在假设 $\tau(A)<\infty$，则利用外测度的定义，对于每个 $n=1,2,\dots$，可以得到 $\{ B_{n,k}\in\mathcal{L},k=1,2,\dots \}$，使得

$$
\bigcup_{k=1}^{\infty}B_{n,k}\supset A,
\sum\limits_{k=1}^{\infty}\mu(B_{n,k})<\tau(A)+\frac{1}{n}.
$$

令 $B=\bigcap_{n=1}^{\infty}\bigcup_{k=1}^{\infty}B_{n,k}$，则有 $B\in\sigma(\mathcal{L})$ 且 $B\supset A$，因此有 $\tau(B)\geq \tau(A)$。另外，我们还可以这样计算：

$$
\tau(B)\leq \tau\left( \bigcup_{k=1}^{\infty}B_{n,k} \right)\leq
\sum\limits_{k=1}^{\infty}\tau(B_{n,k})<\tau(A)+\frac{1}{n},
$$

其中第二个不等号来自于外测度的半可列可加性。令 $n\to \infty$，得到 $\tau(B)\leq \tau(A)$。1 得证。

现在我们来证明 2。因为 $\mu(A_{n})<\infty$，所以 $\forall A\in\mathcal{F}_{\tau}$ 有 $\mu(A\cap A_{n})<\infty$，由 1 的结论，我们可以找到 $B_{n}\supset A\cap A_{n},B_{n}\in\sigma(\mathcal{L})$，且

$$
\tau(B_{n})=\tau(A\cap A_{n})<\infty.
$$

使用测度的可减性得到 $\tau(B_{n}\setminus(A\cap A_{n}))=0$。令 $B=\bigcup_{n=1}^{\infty}B_{n}$，可知 $B\supset\bigcup_{n=1}^{\infty}(A\cap A_{n})=A$，$B\in\sigma(\mathcal{L})$，且有

$$
\begin{align}
\tau(B\setminus A)&=\tau\left( \left( \bigcup_{n=1}^{\infty}B_{n} \right)
\setminus\left( \bigcup_{n=1}^{\infty}A\cap A_{n} \right)
\right) \\
&\leq \tau\left( \bigcup_{n=1}^{\infty}B_{n}\setminus(A\cap A_{n}) \right) \\
&\leq \sum\limits_{n=1}^{\infty}\tau(B_{n}\setminus(A\cap A_{n}))=0
\end{align}
$$

其中第二行成立是因为

$$
\left( \bigcup_{i=1}^{\infty} A_{i}\right)\setminus\left( \bigcup_{i=1}^{\infty}B_{i} \right)
=\bigcup_{i=1}^{\infty}\bigcap_{j=1}^{\infty}A_{i}\setminus B_{j}
\subset \bigcup_{i=1}^{\infty}A_{i}\setminus B_{j},
$$

第三行成立是因为半可列可加性。因此 $\tau(B\setminus A)=0$，命题得证。
:::

这个定理告诉我们，**半环生成的测度实际上已经能够包含很多集合了，其多到和 $\mathcal{F}_{\tau}$ 已经非常相似了**。比如，任何在 $\mathcal{F}_{\tau}$ 中的集合都可以在 $\sigma(\mathcal{F})$ 中找到覆盖它且与他等测度的集合。甚至在加入比 $\sigma$ 有限稍微强一点点的补充条件后，我们可以明确知道这两个等测度集合之间的差是一个零测集。

需要注意的是，在没有补充条件时，我们是不知道 $\tau(B\setminus A)=0$ 的，因为 $\tau(B)$ 可能是无穷大的。比如，在 $\mathbb{R}$ 上，$\mathbb{R}\supset(-\infty,0]$，两者的测度都是无穷大，所以相等，但是两者的差集是 $(0,\infty]$，其测度并不是 0。所以需要通过一些有限性的条件来限制一下。这个条件没有必要时严格有限，只需要类似**强 $\sigma$ 有限**即可。

::: {.callout-note title="利用 $\sigma$ 有限扩展"}
利用 @lem-sigma-finite，其实只要我们让 semi-ring $\mathcal{L}$ 中包含 $\Omega$，则 $\sigma$ 有限就可以推导出补充条件，自然也能够让定理的第 2 条成立。

:::
# 基于域的扩张

上面的讨论告诉我们，因为 semi-ring 结构包含有某种性质，所以从上面去扩张测度是非常好的，可以避免一些问题。那么更进一步，如果我们从一个性质更好的结构（也就是 filed）上扩张测度，会有另外那些额外的收获呢？

后面的定理告诉我们，从 field 上生成的外测度、扩张的测度和 field 本身的测度非常相似，**我们可以使用 field 上的测度来无限逼近扩张测度**。

::: {#prp-ring-extension-outer}

## ring 上的 measure 对外测度的逼近

设 $\mu$ 是 ring$\mathcal{A}$ 上的测度，$\tau$ 是其生成的外测度，则

$$
\forall A\in\sigma(\mathcal{A}),\tau(A)<\infty\implies \forall\epsilon>0,\exists B\in\mathcal{A},\tau(A\Delta B)<\epsilon
$$

:::

::: {.proof}
同样，依据生成外测度的定义，我们有，$\forall\epsilon>0$，存在 $\{ A_{n}\in\mathcal{A},n=1,2,\dots \}$，$\bigcup_{n=1}^{\infty}A_{n}\supset A$，且

$$
\sum\limits_{n=1}^{\infty}\mu(A_{n})<\tau(A)+\frac{\epsilon}{2}.
$$

$\forall N\in\mathbb{N}$，有

$$
\begin{align}
\tau\left( \bigcup_{n=1}^{N}A_{n}\setminus A \right) &\leq
\tau\left( \bigcup_{n=1}^{\infty}A_{n}\setminus A \right) \\
&=\tau\left( \bigcup_{n=1}^{\infty}A_{n} \right)-\tau(A) \\
&\leq \sum\limits_{n=1}^{\infty}\tau(A_{n})-\tau(A) \\
&< \epsilon/2
\end{align}
$$

其实第二行是因为测度的可减性（需要首先证明两个集合都在 $\sigma(\mathcal{A})$ 中，然后，证明 $\tau$ 在 $\sigma(\mathcal{A})$ 上是测度，最后再利用条件 $\tau(A)<\infty$ 才能保证可减性成立）；第 3 行是半可列可加性。

利用级数收敛的相关知识，可以知道，存在充分大的 $N$ 使得 $\sum\limits_{n=N+1}^{\infty}\mu(B_{n})<\epsilon/2$，因此

$$
\begin{align}
\tau\left( A\setminus\left( \bigcup_{n=1}^{N}A_{n} \right) \right)&\leq
\tau\left( \left( \bigcup_{n=1}^{\infty}A_{n} \right)\setminus
\left( \bigcup_{n=1}^{N}A_{n} \right)\right) \\
&\leq \tau\left( \bigcup_{n=1}^{\infty}A_{n} \right)-\tau\left( \bigcup_{n=1}^{N}A_{n} \right) \\
&\leq \tau\left( \bigcup_{n=N+1}^{\infty}A_{n} \right) \\
&\leq \sum\limits_{n=N+1}^{\infty}\tau(A_{n}) <\epsilon/2
\end{align}
$$

其中，第一行是因为 $\bigcup_{n=1}^{\infty}\supset A$，第二行是因为 $\tau$ 作为 $\sigma(\mathcal{A})$ 上测度所拥有的可减性（同样需要先证明第二个集合测度有限），第三行是因为 $\tau$ 有半有限可加性，即

$$
\tau\left( \bigcup_{n=1}^{\infty}A_{n} \right)\leq \tau\left( \bigcup_{n=1}^{N}A_{n} \right)+\tau\left( \bigcup_{n=N+1}^{\infty}A_{n} \right),
$$

第四行是半可列可加性。然后，我们令 $B=\bigcup_{n=1}^{N}A_{n}$，则可知

$$
B\in\mathcal{A},\tau(A\Delta B)=\tau(A\setminus B)+\tau(B\setminus A)<\epsilon/2.
$$

:::

::: {#thm-05-measure-extension-9}

## field 上的测度对扩张测度的逼近

设 $\mathcal{A}$ 是一个 field，$\mu$ 是 $\sigma(\mathcal{A})$ 上的 measure 且在 $\mathcal{A}$ 上 $\sigma$ 有限，如果 $A\in\sigma(\mathcal{A})$ 且 $\mu(A)<\infty$，则有

$$
\forall\epsilon>0,\exists B\in\mathcal{A}\implies \mu(A\Delta B)<\epsilon.
$$

:::
::: {.proof}
因为 field 中包含全集 $\Omega$，因此根据 @thm-measure-extension-2，我们有

$$
\forall C\in\sigma(\mathcal{A})\implies \mu(A)=\tau(A).
$$

其中 $\tau$ 是生成的外测度。然后再根据 @prp-ring-extension-outer，可以直接得到结论。
:::

# 测度空间的完全化

往一个测度空间中添加一些集合，从而得到一个完全的测度空间（定义可见 [完全测度空间的定义](03-measure.qmd#def-complete-measure)），我们称这个完全的测度空间是原来**测度空间的完全化**。

::: {#thm-any-complete}

## 任何测度空间都可被完全化

对于任何测度空间 $(\Omega,\mathcal{F},\mu)$，我们可以定义

$$
\begin{align}
&\tilde{\mathcal{F}}:=\{ A\cup N|
A,B\in\mathcal{F},N\subset B,\mu(B)=0\} \\
&\tilde{\mu}(A\cup N):=\mu(A)
\end{align}
$$

则 $\tilde{\mathcal{F}}$ 是一个 $\sigma$ -field，$(\Omega,\tilde{\mathcal{F}},\tilde{\mu})$ 是一个完全测度空间，且 $\mu(A)=\tilde{\mu}(A),\forall A\in\mathcal{F}$.

:::

::: {.proof}
我们使用 4 个步骤来进行证明这个定理，

1. $\tilde{\mathcal{F}}$ 是一个 $\sigma$-field；
2. $\tilde{\mu}$ 是 well-defined；
3. $\tilde{\mu}$ 是一个测度；
4. $(\Omega,\tilde{\mathcal{F}},\tilde{\mu})$ 是完全测度空间。

首先**第一步**。$\Omega \in  \tilde{\mathcal{F}}$ 是显然的。假设 $\tilde{\mathcal{F}}$ 的元素可以表示为 $A\cup N$，我们有

$$
\begin{align}
(A\cup N)^{c}&=[B^{c}\cap(A\cup N)^{c}]\cup[B\cap(A\cup N)^{c}] \\
&=(B^{c}\cap A^{c})\cup(B\cap A^{c}\cap N^{c}) \\
\end{align}
$$

可以看到，$B^{c}\cap A^{c}\in\mathcal{F}$，$B\cap A^{c}\cap N^{c}\subset B$，所以 $(A\cup N)^{c}\in \tilde{\mathcal{F}}$。

假设 $A_{n}\cup N_{n}\in \tilde{\mathcal{F}}$，则有

$$
\begin{align}
&A:=\bigcup_{n=1}^{\infty}A_{n},\quad
N:=\bigcup_{n=1}^{\infty}N_{n},\quad
B:=\bigcup_{n=1}^{\infty}B_{n} \\
&\mu(B)=0,\quad N\subset B \implies
\bigcup_{n=1}^{\infty}(A_{n}\cup N_{n})=A\cup N\in \tilde{\mathcal{F}}
\end{align}
$$

因此，$\tilde{\mathcal{F}}$ 是一个 $\sigma$-field。

然后**第二步**，我们需要证明 $\tilde{\mu}$ 是 well-defined，即对于一个集合，其会得到相同的值。若 $A_{1}\cup N_{1}=A_{2}\cup N_{2}\in \tilde{\mathcal{F}}$，则

$$
\tilde{\mu}(A_{1}\cup N_{1})=\mu(A_{1})=\mu(A_{1}\cup B_{1}\cup B_{2})\geq \mu(A_{2})=\tilde{\mu}(A_{2}\cup N_{2})
$$

其中 $B_{1}\supset N_{1},B_{2}\supset N_{2}$。同理可得 $\tilde{\mu}(A_{1}\cup N_{1})\leq  \tilde{\mu}(A_{2}\cup N_{2})$,因此得到

$$
\tilde{\mu}(A_{1}\cup N_{1})=\tilde{\mu}(A_{2}\cup N_{2}).
$$

**第三步**，我们来证明 $\tilde{\mu}$ 是 $\tilde{\mathcal{F}}$ 上的一个测度。空集为 0 和非负性显而易见，我们只需要证明可列可加性即可。假设 $\{ A_{n}\cup N_{n}\in \tilde{\mathcal{F}},n=1,2,\dots \}$ 两两不交，则 $\{ A_{n} \in \mathcal{F},n=1,2,\dots \}$ 也两两不交，从而有

$$
\begin{align}
\tilde{\mu}\left( \bigcup_{n=1}^{\infty}(A_{n}\cup N_{n}) \right)
=\mu\left( \bigcup_{n=1}^{\infty}A_{n} \right)=\sum\limits_{n=1}^{\infty}\mu(A_{n})
=\sum\limits_{n=1}^{\infty}\tilde{\mu}(A_{n}\cup N_{n})
\end{align}
$$

其中第一个等号是因为 $\bigcup_{n=1}^{\infty}(A_{n}\cup N_{n})=\left(\bigcup_{n=1}^{\infty}A_{n}\right)\cup\left( \bigcup_{n=1}^{\infty}N_{n} \right)$，这样 $\left( \bigcup_{n=1}^{\infty}N_{n} \right)$ 也是一个零测集的子集，所以其可以看做是 $\tilde{\mathcal{F}}$ 的元素，可以利用 $\tilde{\mu}$ 的定义来得到。第二个等号是测度的可列可加性。第三个等号是利用 $\tilde{\mu}$ 的定义。因此，第三步得证。

**第四步**，证明完全性。若 $A\cup N\in \tilde{\mathcal{F}}$，$\tilde{\mu}(A\cup N)=0$，$\forall C \subset A\cup N$，则存在一个 $B\in\mathcal{F},N\subset B$，满足

$$
\mu(A\cup B)\leq \mu(A)+\mu(B)=\tilde{\mu}(A\cup N)+\mu(B)=0
$$

这里，$A\cup B\in\mathcal{F},C\subset A\cup B,C=C\cup \emptyset$，所以根据 $\tilde{\mathcal{F}}$ 的定义，$C\in \tilde{\mathcal{F}}$。至此，我们完成了证明。
:::

进一步我们可以证明，使用外测度得到的测度 $\mathcal{F}_{\tau}$ 是 semi-ring 生成的测度的完全化（但首先需要保证测度的 $\sigma$ 有限性）。

::: {#thm-05-measure-extension-11}

## semi-ring 生成的测度空间的完全化

设 $\tau$ 是 semi-ring $\mathcal{L}$ 上**$\sigma$ 有限测度**$\mu$ 生成的外测度，则 $(\Omega,\mathcal{F}_{\tau},\tau)$ 是 $(\Omega,\sigma(\mathcal{L})),\mu$ 的完全化。

:::
::: {.proof}
令 $\mathcal{F}=\sigma(\mathcal{L})$，我们需要证明 $\mathcal{F}_{\tau}=\tilde{\mathcal{F}}$.
$\forall A\in\mathcal{F}_{\tau}$，根据 @thm-extension-diff，可以得到

$$
\exists C\in\mathcal{F},C\supset A\implies \tau(C\setminus A)=0.
$$

可以知道，$C\setminus A\in\mathcal{F}_{\tau}$，因此可以再用一遍这个定理，得到

$$
\exists B\in\mathcal{F},B\supset C\setminus A\implies \tau(B)=\tau(C\setminus A)=0.
$$

进而我们可以将 $A$ 表示为

$$
\begin{align}
A&=(A\cap B^{c})\cup(A\cap B)\\
&=([(C\setminus A)\cup A]\cap B^{c})\cup(A\cap B)\\
&=(C\cap B^{c})\cup(A\cap B)
\end{align}
$$

其中第二个等号是因为 $B\supset C\setminus A$，第三个等号是因为 $C\supset A$。注意，$C\cap B^{c}\in\mathcal{F}$，$A\cap B\subset B\in\mathcal{F}$ 且 $\tau(B)=0$，也就是说我们把 $A$ 写成了 $A\cup N$ 的形式，即 $A\in \tilde{\mathcal{F}}$ 中。

$\forall A\in \tilde{\mathcal{F}}$，因此其可以表示为

$$
A=A_{0}\cup N,A_{0}\in\mathcal{F},N\subset B\in\mathcal{F},\tau(B)=0.
$$

根据 @thm-any-complete，$\mathcal{F}_{\tau}$ 具有完全性，则必有 $N\in\mathcal{F}_{\tau}$，因此 $A\in\mathcal{F}_{\tau}$。综合以上两部分的证明，得到 $\mathcal{F}_{\tau}=\tilde{\mathcal{F}}$
:::
