---
title: "Lp 空间"
draft: false
aliases:
  - Lp空间
author:
  - 荣志炜
tags:
  - Lp空间
  - Holder不等式
  - Minkowski不等式
created: 2025-11-11 22:35
updated: 2026-04-29 12:48
order: 9
---

# 背景

Lp 空间的出现是分析学从具体函数向量空间化的关键一步，其背景在于为可测函数集合赋予了完备的拓扑结构。 在测度理论的基础上，通过勒贝格积分定义函数的 p- 范数，使得我们可以衡量**函数的大小**和**函数间的距离**，这是将**有限维欧氏空间的几何直观推广到无穷维函数空间的自然延伸**。 这一构造最重要的意义在于其**完备性**：**Lp 空间是巴拿赫空间（完备的赋范线性空间），这意味着任何柯西序列都收敛于空间内部的一点，从而保证了极限运算的封闭性与稳定性**，为泛函分析理论的建立提供了最重要和最典型的范例。

在高等概率论中，整个理论框架都构建于测度论之上，一个概率空间本质上就是一个总测度为 1 的测度空间。在此背景下，Lp 空间的意义尤为重大：**它为随机变量的分类和收敛性分析提供了严格的数学语言。一个随机变量可看作是概率空间上的一个可测函数，其 p 次绝对矩的有限性就等价于该函数属于相应的 Lp 空间。** 因此，Lp 空间成了研究随机变量不同性质（如方差、偏度）的天然场所，并且定义了概率论中重要的收敛模式，例如 **“均方收敛”**（即 L2 空间中的收敛），为中心极限定理等核心结果的精确阐述与证明奠定了不可或缺的分析基础。

# 定义

::: {#def-lp}

## Lp 空间

设 $(X,\mathcal{F},\mu)$ 是一个测度空间，$1\leq p<\infty$，定义

$$
L_{p}(X,\mathcal{F},\mu):=\left\{  f|f measurable, \int _{X}
\left| f \right| ^{p} \, d\mu  <\infty\right \},
$$

简记为 $L_{p}$。此外，我们进一步定义

$$
||f||_{p}:=\left[ \int _{X}|f|^{p} \, d\mu  \right] ^{1/p},
$$

并且记 $\lVert f \rVert=\lVert f \rVert_{1}$，容易有下面的结论

$$
f\in L_{p}\iff \lVert f \rVert _{p}<\infty.
$$

:::

# 性质

$L_{p}$ 空间中的函数存在一些值得讨论的性质，特别是一些不等式。

## 线性封闭性

首先我们需要证明两个引理。

::: {#lem-lp-power-sum-bound}

## Lemma

对任何 $a,b\in\mathbb{R}$ 和 $1\leq p<\infty$，有

 $$
\left| a+b \right| ^{p}\leq 2^{p-1}(\left| a \right| ^{p}+\left| b \right| ^{p})
$$

:::

::: {.proof}
当 $a=0$ 或 $b=0$ 或 $p=1$ 的时候，结论显然成立。我们现在只需要去证明其他的情况即可。
首先，我们来证明 $a,b\in\mathbb{R}^{+}$，不等式 [eq-lp-convex-auxiliary](#eq-lp-convex-auxiliary) 成立。

$$
2^{p-1}[x^{p}+(1-x)^{p}]\geq 1,\forall x \in (0,1)
$$

<span id="eq-lp-convex-auxiliary"></span>

这个是容易证明的，只需要使用基础的微积分就可以解决。先对函数

$$
f(x)=2^{p-1}[x^{p}+(1-x)^{p}]
$$

求导，得到其导函数为

$$
f'(x)=2^{p-1}p[x^{p-1}-(1-x)^{p-1}].
$$

<span id="eq-lp-convex-derivative"></span>

我们来分析 [eq-lp-convex-derivative](#eq-lp-convex-derivative)，当 $x$ 较小（接近 0）的时候，$f'(x)<0$，当 $x$ 较大（接近 1）的时候，$f'(x)>0$，所以 $f(x)$ 在 $(0,1)$ 中存在一个极小值，是 $x=0.5$ 的时候。此时，我们有 $f(1/2)=1$。不等式 [eq-lp-convex-auxiliary](#eq-lp-convex-auxiliary) 得到证明。

因此，对于任何 $a,b\in\mathbb{R}^{+}$，我们有

$$
\begin{align}
&2^{p-1}\left[ \left( \frac{a}{a+b} \right)^{p}+\left( \frac{b}{a+b} \right) ^{p}\right]\geq 1
\implies
2^{p-1}[a^{p}+b^{p}]\geq(a+b)^{p}.
\end{align}
$$

当 $a,b\in\mathbb{R}$ 时，有

$$
\left| a+b \right| \leq \left| a \right| +\left| b \right| ,
$$

因此，有

$$
(\left| a+b \right|)^{p}\leq
(\left| a \right| +\left| b \right|)^{p}\leq
2^{p-1}[|a|^{p}+|b|^{p}].
$$

问题得证。
:::
由上面的引理，关于 $L_{p}$ 我们有下面的性质：

::: {#thm-lp-linear-closure}

## 线性封闭性

$L_{p}$ 对线性运算是封闭的，即 $\forall 1\leq p<\infty,\forall a,b\in\mathbb{R}$，有

$$
f,g\in L_{p}\implies af+bg\in L_{p}.
$$

:::

::: {.proof}

$$
\begin{align}
\int \left| af+bg \right|^{p}  \, d\mu \leq 
2^{p-1}\left[ 
\int \left| af \right|^{p} \, d\mu+\int \left| bg \right|^{p}  \, d\mu
\right] \leq
2^{p-1}\left[ 
|a|^{p}\int \left| f \right|^{p} \, d\mu+|b|^{p}\int \left| g \right|^{p}  \, d\mu
\right]
<\infty.
\end{align}
$$

:::

## 积分不等式

### Holder 不等式

同样，首先我们先需要证明一个引理。

::: {#lem-young-inequality}

## Lemma

若 $1<p,q<\infty$ 且 $\frac{1}{p}+\frac{1}{q}=1$，则对于任何 $a,b\in\mathbb{R}\setminus\mathbb{R}^{-}$，有

$$
a^{1/p}b^{1/q}\leq \frac{a}{p}+\frac{b}{q},
$$

而且等号成立当且仅当 $a=b$。

:::

::: {.proof}
不难看出 $ab=0$ 时，引理成立。所以，不妨设 $a,b\in\mathbb{R}^{+}$，容易证明上述不等式等价于证明

$$
\left[ \frac{a}{b} \right]^{1/p}\leq \frac{1}{p}\frac{a}{b}+\frac{1}{q}.
$$

<span id="eq-young-ratio-form"></span>

令 $\alpha=\frac{1}{p}$，证明不等式 [eq-young-ratio-form](#eq-young-ratio-form) 等价于证明 $\forall x \in\mathbb{R}^{+}$ 有

$$
x^{\alpha}\leq 1+\alpha(x-1).
$$

<span id="eq-young-tangent-bound"></span>

我们可以使用基本微积分的方式来证明上式：
令 $f(x)=x^{\alpha}-\alpha(x-1)$，可以得到其导函数和二次导函数有

$$
\begin{align}
&f'(x)=\alpha x^{\alpha-1}-\alpha, \\
&f''(x)=\alpha(\alpha-1)x^{\alpha-2},
\end{align}
$$

注意，这里的 $\alpha>1$。容易知道，$\forall a\in\mathbb{R}^{+},f''(x)>0$，$f(x)$ 是一个凸函数，有一个极小值。这个极小值是 $x=1$，此时 $f(1)=1$。这就证明了不等式 [eq-young-tangent-bound](#eq-young-tangent-bound)，并且等号当且仅当 $x=1$ 时成立。利用我们前面的论述，引理得证。
:::

下面，我们来证明下面的 Holder 不等式。

::: {#thm-holder-inequality}

## Holder 不等式

如果 $1<p,q<\infty$，并且满足 $\frac{1}{p}+\frac{1}{q}=1$，则对于任何 $f,g\in L_{p}$，有

$$
\lVert fg \rVert \leq \lVert f \rVert _{p}\lVert g \rVert _{q},
$$

并且等号成立的充分必要条件是存在不全为 0 的 $\alpha,\beta\geq 0$ 使得

$$
a\lvert f \rvert ^{p}=\beta \lvert g \rvert ^{q}\ a.e.
$$

:::

::: {.proof}
不难看出，如果 $f=0$ a.e.或 $g=0$ a.e.，等号成立。因此，我们不妨认为 $f,g\neq 0$ a.e.，也就是 $0<\lVert f \rVert_{p},\lVert g \rVert_{q}<\infty$，令引理中的

$$
a=\left( \frac{\lvert f \rvert }{\lVert f \rVert }_{p} \right)^{p},\quad
b=\left( \frac{\lvert g \rvert }{\lVert g \rVert }_{q} \right)^{q},
$$

根据 @lem-young-inequality，我们有

$$
\frac{\lvert fg \rvert }{\lVert f \rVert _{p}\lVert g \rVert _{q}}\leq
\frac{1}{p}\frac{\lvert f \rvert ^{p}}{\lVert f \rVert _{p}^{p}}+
\frac{1}{q}\frac{\lvert g \rvert ^{q}}{\lVert g \rVert ^{q}_{q}}
\ a.e.,
$$

<span id="eq-holder-normalized-bound"></span>

两端同时取积分，得到

$$
\lVert fg \rVert \leq \lVert f \rVert _{p}\lVert g \rVert _{q}.
$$

<span id="eq-holder-integral-bound"></span>

注意到，由不等式 [eq-holder-normalized-bound](#eq-holder-normalized-bound) 可以推知

$$
\frac{1}{p}\frac{\lvert f \rvert ^{p}}{\lVert f \rVert _{p}^{p}}+
\frac{1}{q}\frac{\lvert g \rvert ^{q}}{\lVert g \rVert ^{q}_{q}}-
\frac{\lvert fg \rvert }{\lVert f \rVert _{p}\lVert g \rVert _{q}}\geq 0
\ a.e.
$$

根据前面的性质，我们可以知道，不等式 [eq-holder-integral-bound](#eq-holder-integral-bound) 中等式成立当且仅当 [eq-holder-normalized-bound](#eq-holder-normalized-bound) 等式成立。有根据 @lem-young-inequality，等号成立的充分比较条件为

$$
\left( \frac{\lvert f \rvert }{\lVert f \rVert }_{p} \right)^{p}=
\left( \frac{\lvert g \rvert }{\lVert g \rVert }_{q} \right)^{q}
\iff
\lVert g \rVert ^{q}_{q}\lvert f \rvert ^{p}=
\lVert f \rVert _{p}^{p}\lvert g \rvert ^{q},
$$

<span id="eq-holder-equality-condition"></span>

考虑到 $fg=0$ a.e.的情况，这个条件就是定理中所描述的情况。我们可以简单证明一下，首先，容易知道

$$
\lVert g \rVert ^{q}_{q}\lvert f \rvert ^{p}=
\lVert f \rVert _{p}^{p}\lvert g \rvert ^{q}
$$

和 $fg=0$ a.e.蕴含定理中的条件；那么若定理中的条件成立，并且 $fg\neq 0$ a.e.时，我们有

$$
\alpha \lVert f \rVert _{p}^{p}=\beta \lVert g \rVert ^{q}_{q} \implies
\frac{\alpha \lvert f \rvert ^{p}}{\alpha \lVert f \rVert _{p}^{p}}
=\frac{\beta \lvert g \rvert ^{q}}{\beta \lVert g \rVert ^{q}_{q}}
\implies\frac{\lvert f \rvert ^{p}}{\lVert f \rVert _{p}^{p}}
=\frac{\lvert g \rvert ^{q}}{\lVert g \rVert ^{q}_{q}},
$$

也就是式 [eq-holder-equality-condition](#eq-holder-equality-condition)。
:::

Holder 不等式的重要性不言而喻，更加重要的是要意识到什么时候去使用它。后面我们会知道，$L_{p}$ 其实是一个范数空间，所以涉及到**两个函数相乘的范数**或**两个函数范数乘积**时，@thm-holder-inequality 可能会起到作用。

### Cauchy-Schwarz 不等式

根据 @thm-holder-inequality, 我们可以得到另外一个使用非常多的不等式, 即

::: {#thm-cauchy-schwarz-inequality}

## Cauchy-Schwarz 不等式

对 $f,g\in L_{2}$，有

$$
\lVert fg \rVert^{2} \leq \lVert f \rVert _{2}^{2}\lVert g \rVert _{2}^{2},
$$

并且等号成立的充分必要条件是存在不全为 0 的 $\alpha,\beta\geq 0$ 使得

$$
a\lvert f \rvert ^{2}=\beta \lvert g \rvert ^{2}\ a.e.
$$

:::

::: {.proof}
令 $p=q=2$, 然后利用 Holder 不等式即可.
:::
该不等式的一个重要作用是去证明 @thm-covariance-inequality.

### Liapounov 不等式

根据 @thm-holder-inequality, 我们还可以得到另外一个重要的不等式, 其描述了上标变化时的行为.

::: {#thm-liapounov-inequality}

## Liapounov 不等式

对于任意 $1\leq r\leq s$, 假设 $f \in L_{s}$, 则有

$$
\lVert f \rVert _{r}\leq \lVert g \rVert _{s}.
$$

:::

::: {.proof}
对随机变量 $\lvert f \rvert^{r}$ 和 $1$, 以及 $p=\frac{s}{r},q=1 / \left( 1 - \frac{1}{p} \right)$ 应用 Holder 不等式.
:::

### Minkowski 不等式

我们可以使用 @thm-holder-inequality 直接得到 minkowski 不等式。

::: {#thm-minkowski-inequality}

## Minkowski 不等式

设 $1\leq p<\infty$，则对于任何 $f,g\in L_{p}$，有

$$

\lVert f+g \rVert _{p}\leq \lVert f \rVert _{p}+
\lVert g \rVert _{p}.
$$

并且等号成立的充分必要条件是
(1) 当 $p=1$ 时，$fg\geq 0$ a.e.；
(2) 当 $1<p<\infty$ 时，存在不全为 0 的 $\alpha,\beta\geq 0$ 使得 $\alpha f=\beta g$ a.e.。

:::

::: {.proof}
当 $p=1$ 时，结论显然成立。因为根据实数的性质：
$\forall a,b\in\mathbb{R}$，有

$$
\lvert a+b \rvert \leq \lvert a \rvert +\lvert b \rvert ,
$$

其中等号成立当且仅当 $ab\geq 0$。
当 $1<p<\infty$，记 $q=\frac{p}{p-1}$，可知 $\frac{1}{p}+\frac{1}{q}=1$，则根据 @thm-holder-inequality，有

$$
\begin{align}
\lVert f+g \rVert _{p}^{p}&=
\int _{x}\lvert f+g \rvert ^{p} \, d\mu \\ 
&\leq \int _{X}\lvert f \rvert \lvert f+g \rvert ^{p-1} \, d\mu
+\int _{X}\lvert g \rvert \lvert f+g \rvert ^{p-1} \, d\mu \\
&\leq \lVert f \rVert _{p}\lVert \lvert f+g \rvert ^{p-1} \rVert _{q}
+\lVert g \rVert _{p}\lVert \lvert f+g \rvert ^{p-1} \rVert _{q} \\
&=(\lVert f \rVert _{p}+\lVert g \rVert _{p})\lVert f+g \rVert _{p}^{p-1}
\end{align}
$$

<span id="eq-minkowski-holder-step"></span>

上述第三行使用到了 @thm-holder-inequality。当 $\lVert f+g \rVert_{p}=0$ 时， @thm-minkowski-inequality 显然成立，并且等号成立当且仅当 $f=g=0$ a.e.。当 $\lVert f+g \rVert_{p}>0$ 时，则 [eq-minkowski-holder-step](#eq-minkowski-holder-step) 式两端可以同时除以 $\lVert f+g \rVert_{p}^{p-1}$，从而得到 @thm-minkowski-inequality。等号当且仅当 [eq-minkowski-holder-step](#eq-minkowski-holder-step) 中两个不等号中等号成立。这意味着：
(1) $fg\geq 0$ a.e.；
(2) $\exists$ 不全为 0 的 $a,b\geq 0$ 和不全为 0 的 $c,d\geq 0$，满足

$$
a\lvert f \rvert ^{p}=b\lvert f+g \rvert ^{p}\ a.e., \quad
c\lvert g \rvert ^{p}=d\lvert f+g \rvert ^{p}\ a.e.
$$

这两个条件等价于定理中的条件 (2)。
:::
当遇到两个函数**加和的范数**或**范数的加和**时，可以考虑 @thm-minkowski-inequality。此外，可以知道，该不等式其实是**三角不等式**（$\lvert a+b \rvert\leq \lvert a \rvert+\lvert b \rvert$）的推广。而三角不等式是范数定义的重要部分。 @thm-minkowski-inequality 可以轻松推广到超过两个随机变量的情况.

### Essen-Bahr 不等式

其不止将 @thm-minkowski-inequality 推广到了超过两个随机变量的情况, 并且得到了更紧的形式.

::: {#thm-essen-bahr-inequality}

## Essen-Bahr 不等式

假设存在 $f_{1},\dots,f_{n}\in L_{p}$, 并且有 $\mathbb{E}f_{i}=0,\forall i=1,\dots,n$. 则有

$$
\mathbb{E}\left\lvert  \sum\limits_{i=1}^{n}f_{i}  \right\rvert ^{p}\leq
C_{p,n}\sum\limits_{i=1}^{n}\mathbb{E}\lvert f_{i} \rvert ^{p},
$$

其中
- 若 $p \in [1,2]$, 则 $C_{p,n}=C_{p}$ 仅依赖于 $p$.
- 若 $p>2$, 则 $C_{p,n}=\frac{C_{p}}{n^{1-p/2}}$, 其中 $C_{p}$ 仅依赖于 $p$.

:::

::: {.proof}
略
:::

### Jensen 不等式

::: {#thm-jensen-inequality}

## Jensen 不等式

存在一个 convex function $g$ 定义在一个 open convex $A\in \mathbb{R}^{k}$, $f$ 是一个定义在概率空间中的随机向量, 并且有 $\mathbb{E}f<\infty$ 和 $P(f\in A)=1$, 则有

$$
g(\mathbb{E}f)\leq \mathbb{E}(g(f)).
$$

若 $g$ 是 strict convex, 则 $\leq$ 可以替换为 $<$, 除非 $P(g(f)=\mathbb{E}g(f))=1$.

:::

::: {.proof}
由 convex 的性质可知, $\forall y\in A,\exists a_{y}\in A$,

$$
g(x)\geq g(y)+a_{y}(x-y)^{T}, \forall x \in A.
$$

<span id="eq-convex-supporting-hyperplane"></span>

又因为

$$
P(f\in A)=1\implies \mathbb{E}f\in A,
$$

所以, 令 $x=f,y=\mathbb{E}f$, 然后取期望, 得到

$$
\mathbb{E}(g(f))\geq g(\mathbb{E}f).
$$

其中 $g(\mathbb{E}f)$ 的积分存在性由 @thm-integrable-exists 保证.

如果 $f$ 是 strict convex, 则式 [eq-convex-supporting-hyperplane](#eq-convex-supporting-hyperplane) 中的 $\geq$ 变为 $>$, 则加上 @prp-order (3), 就完成了最后的证明.

:::

## $L_{\infty}$

实际上，上述的结论可以推广至 $p=\infty$ 的情况。

::: {#def-linfty}

## Definition

定义 $(X,\mathcal{F},\mu)$ 上的所有 a.e. 有界可测函数的全体为 $L_{\infty}(X,\mathcal{F},\mu)$，简记为 $L_{\infty}$。对于其中的每个函数，定义

$$
\lVert f \rVert _{\infty}=\inf\{ a\in\mathbb{R}^{+}|\mu(\lvert f \rvert >a)=0 \}.
$$

:::

::: {.callout-note title="可以理解为在去掉一些测度为 0 点后， $f$ 函数绝对值的最大值或上确界。"}

:::
对于 $L_{\infty}$，我们也可以得到类似 @thm-holder-inequality 和 @thm-minkowski-inequality 的结论。

::: {#thm-holder-minkowski-linfty}

## Holder 和 Minkowski 不等式扩展

若 $f\in L_{1},g\in L_{\infty}$，则有

$$
\lVert fg \rVert \leq \lVert f \rVert \lVert g \rVert _{\infty}.
$$

若 $f,g\in L_{\infty}$，则有

$$
\lVert f+g \rVert _{\infty}\leq \lVert f \rVert _{\infty}+\lVert g \rVert _{\infty}.
$$

:::

::: {.proof}
根据 @def-linfty，我们有 $\forall \epsilon>0$，$\lvert g \rvert\leq \lVert g \rVert_{\infty}+\epsilon$ a.e.。所以有

$$
\begin{align}
\lVert fg \rVert =\int _{X}\lvert fg \rvert  \, d\mu
\leq (\lVert g \rVert _{\infty}+\epsilon)\int _{X}\lvert f \rvert  \, d\mu
\leq \lVert g \rVert _{\infty}\lVert f \rVert+\epsilon\lVert f \rVert ,
\end{align}
$$

令 $\epsilon\to \infty$，我们得到第一个结论。
同样的道理，我们有

$$
\lvert f \rvert\leq \lVert f \rVert_{\infty}+\epsilon_{1},\quad
\lvert g \rvert\leq \lVert g \rVert_{\infty}+\epsilon_{2},\quad
\forall\epsilon_{1},\epsilon_{2}>0,\quad a.e.
$$

进而有

$$
\lvert f+g \rvert \leq \lvert f \rvert +\lvert g \rvert \leq
\lVert f \rVert_{\infty}+\lVert g \rVert _{\infty}+\epsilon_{1}+
\epsilon_{2}\quad a.e.
$$

这意味着

$$
\lVert f+g \rVert _{\infty}\leq \lVert f \rVert _{\infty}+\lVert g \rVert _{\infty}.
$$

:::
注意到，@thm-holder-minkowski-linfty 中没有关于等式成立的条件。

## 线性赋范空间

根据上面得到的一些定理，我们实际上可以认识到，$L_{p}$ 实际上是一个具有特定代数和拓扑性质的结构。

::: {.callout-note}
下面在证明中使用到了等价类的概念，如果不严格地来说，可以不使用这个概念，直接认为 $f=g\ a.e.$ 蕴含 $f,g$ 在 $L_{p}$ 中是相等的即可。当然这实际上是隐式地使用了等价类。
**Theorem: 线性空间**
$\forall 1\leq p\leq \infty$， $L_{p}$ 是一个实数域上的线性空间。

:::
::: {.proof}
因为有 almost everywhere 的存在，所以我们需要多做一些处理。

首先，我们可以证明，almost everything equal 是一个等价关系，所以我们可以依据等价关系来构建不同的等价类，函数 $f$ 所对应的等价类用 $\tilde{f}$ 表示。现在我们可以认为空间 $L_{p}$ 的元素是这些等价类 $\tilde{f}$。

现在我们来定义元素之间的加法和数乘。我们定义

$$
\tilde{f}+\tilde{g}:=\tilde{f+g},\quad
a \tilde{f}:=\tilde{af},
$$

容易证明，以上定义的运算是 well-defined。

然后我们需要证明以上的运算是封闭的。当 $1\leq p<\infty$ 时，可以通过 @thm-lp-linear-closure 直接得到。当 $p=\infty$ 时，显然也是封闭的。

其次，我们需要去证明加法的结合律、交换律、单位元和逆元。结合律和交换律依赖于实数的结合律和交换律，容易证明是成立的。单位元是 $\tilde{0}$ 函数，逆元是 $-\tilde{f}$ ，容易证明是成立的。

最后我们需要证明数乘的域单位元性质、对向量加法的分配率、对域加法的分配率、对域乘法的分配率。容易证明是成立的。于是，上述定理是成立的。
:::

::: {#thm-lp-normed-space}

## 线性赋范空间

$\forall 1\leq p\leq \infty$，$\lVert f \rVert_{p}$ 是一个范数，所以 $(L_{p},\lVert \cdot \rVert)$ 是一个线性赋范空间。

:::

::: {.proof}
我们只需要证明 $\lVert \cdot \rVert$ 是一个范数即可。首先，我们可以去定义

$$
\lVert \tilde{f} \rVert _{p}:=\lVert f \rVert _{p},
$$

容易证明，这个定义是 well-defined。

这需要我们证明以下三个条件：
(1) $\lVert \tilde{f} \rVert_{p}\geq 0;\quad \lVert \tilde{f} \rVert_{p}=0\iff \tilde{f}=\tilde{0}\text{或}f=0\ a.e.$；
(2) $\lVert a\tilde{f} \rVert_{p}=\lvert a \rvert\lVert \tilde{f} \rVert_{p},\forall a\in \mathbb{R}$；
(3) 三角不等式。

(1) 和 (2) 的证明是容易的，(3) 直接使用 @thm-minkowski-inequality 和 @thm-holder-minkowski-linfty 的结论即可。
:::

## 完备性

类似于数学分析中的柯西准则, 我们有如下的定理:

::: {#thm-09-lp-spaces-14}

## $L_{p}$ 空间的完备性

设 $0<p\leq\infty$, 若 $\{ f_{n} \}\subset L_{p}$, 并且满足

$$
\lim_{ n,m \to \infty } \lVert f_{n}-f_{m} \rVert_{p} =0,
$$

则存在 $f\in L_{p}$ 使得

$$
\lim_{ n \to \infty } \lVert f_{n}-f \rVert _{p}=0.
$$

:::
::: {.proof}
略
:::

因此, 我们可以定义 $L_{p},0<p\leq \infty$ 中的距离:

$$
\rho(f,g):= \lVert f-g \rVert _{p}.
$$

以上定理表明该**距离具有完备性. 因此当 $0<p<1$ 时, $L_{p}$ 是一个完备的距离空间. 当 $1\leq p\leq \infty$ 时, $L_{p}$ 是一个 [Banach 空间](https://zh.wikipedia.org/wiki/%E5%B7%B4%E6%8B%BF%E8%B5%AB%E7%A9%BA%E9%97%B4), 也就是一个完备的 [赋范线性空间](08-integration.qmd#85cd4a) .**

## $0<p<1$

以上的讨论只集中在 $1\leq p\leq \infty$ 的范围内，那对于 $0<p<1$ 的范围内，会有怎样的结论呢？

我们依然定义

$$
L_{p}:=\left\{  f\mid\int _{X}\lvert f \rvert^{p}  \, d\mu <\infty  \right\},
$$

**但是 $\lVert \cdot \rVert_{p}$ 的定义与之前不同（没有 $1/p$ 次幂）**：

$$
\lVert f \rVert _{p}:=\int _{X}\lvert f \rvert^{p}  \, d\mu.
$$

这导致了

$$
\lVert af \rVert _{p}=\lvert a \rvert ^{p}\lVert f \rVert _{p},
$$

所以其不满足范数定义的第二个条件，$\lVert \cdot \rVert_{p}$ 不再是范数。但是，我们可以证明一个 Minkowski 不等式的类似物。

::: {#lem-quasi-norm-subadditivity}

## Lemma

若 $0<p<1$，则 $\lvert a+b \rvert^{p}\leq \lvert a \rvert^{p}+\lvert b \rvert^{p}$，$\forall a,b\in\mathbb{R}$。

:::

::: {.proof}
我们首先证明 $f(x)=(1-x)^{p}+x^{p}\geq 1,\forall x \in(0,1)$。
我们可以直接使用微积分的方法，得到

$$
\begin{align}
&f'(x)=p(x^{p-1}-(1-x)^{p-1}), \\
&f''(x)=p(p-1)(x^{p-2}+(1-x)^{p-2}),
\end{align}
$$

因为 $p<1$，所以 $f''(x)\leq 0$，也就是说 $f(x)$ 是一个凹函数，$f'(x)=0\implies x=1/2$ 时 $f(x)=2^{1-p}$ 取到最大值，下界在 $x\to0,1$ 时取到，
我们有

$$
\lim_{ x \to 0 }f(x) =\lim_{ x \to 1 } f(x)=1,
$$

所以 $f(x)\geq 1,\forall x \in(0,1)$。

当 $a,b>0$ 时，利用上面证明的结论，我们有

$$
\begin{align}
\left( \frac{a}{a+b} \right)^{p}+\left( \frac{b}{a+b} \right)^{p}\geq 1
\implies 
(a+b)^{p}\leq a^{p}+b^{p} \implies
\lvert a+b \rvert ^{p}\leq \lvert a \rvert ^{p}+\lvert b \rvert ^{p}.
\end{align}
$$

当 $a$ 或 $b=0$ 时，则结论显然成立。
当 $a,b\in\mathbb{R}$ 时，则

$$
\lvert a+b \rvert ^{p}\leq \lvert \lvert a \rvert +\lvert b \rvert  \rvert ^{p}\leq\lvert a \rvert ^{p}+\lvert b \rvert ^{p}.
$$

证毕。
:::

::: {#thm-quasi-minkowski-inequality}

## Minkowski 类似物

若 $0<p<1$，则 $\lVert f+g \rVert_{p}\leq \lVert f \rVert_{p}+\lVert g \rVert_{p}$。

:::

::: {.proof}
直接使用 @lem-quasi-norm-subadditivity 即可完成证明。
:::

这使得我们可以通过这个定理形成一个 $L_{p}$ 上的距离，从而构成一个**距离空间**。

::: {.callout-note title="Question"}
为什么不加 $1/p$ 次幂？这会带来什么样的影响？

:::
注意，当 $1\leq p\leq \infty$ 时，我们可以通过范数来诱导一个距离。所以当 $0<p\leq \infty$ 时，$L_{p}$ 都是一个距离空间，我可以讨论其上的拓扑性质。最**显然的一个结论是：在这个距离下，$L_{p}$ 是完备的。因此，$0<p<1$ 时，$L_{p}$ 是一个完备的距离空间；$1\leq p\leq \infty$ 时，$L_{p}$ 是一个 Banach 空间。**相关的信息将在 [19_收敛理论](19-convergence-theory.qmd) 中进一步进行讨论。

::: {.callout-important title="不等式逐步证明方法"}
这一节中证明了多个不等式，这些不等式的证明方法存在一些共性，我将其称为**不等式逐步证明方法**，总结如下。
1. 我们首先可以想一想，当将结论集中在一个子集中时，是否可以将结论推广至全集。比如，我们可以先假设结论在 $\mathbb{R}^{+}$ 上成立，看看是否可以在此基础上推广至 $\mathbb{R}$。这样，我们就可以把问题集中在这个子集（$\mathbb{R}^{+}$）上解决，降低了问题的复杂度。
2. 在上一步的基础上，我们查看一下是否可以削减变元的数量，比如将两个变元（$a,b$）修改为一个变元（$x$）。这样，我们实际上等价于在证明只含有一个变量的函数的不等式。
3. 在上一步的基础上，我们就可以利用简单微积分的知识来进行证明这个函数一个变量的函数的不等式。然后反向推导到第一层，完成整个证明。
:::
