---
title: "随机向量"
draft: false
aliases:
  - 随机向量
  - 高维随机变量
author:
  - 荣志炜
tags:
  - 随机向量
  - 可测性
  - 联合分布
  - 边缘分布
  - 联合密度
date: 2025-11-28 16:33
date-modified: last-modified
order: 15
---

# 引言

[有限乘积空间](13-finite-product-spaces.qmd)主要研究定义域为乘积空间的实值可测函数

$$
g:\left(\prod_{k=1}^{n}X_k,\bigotimes_{k=1}^{n}\mathcal F_k\right)\longrightarrow\mathbb R.
$$

随机向量则沿着相反的方向出现：它把一个抽象样本点映到高维欧氏空间，

$$
f=(f_1,\ldots,f_n):(\Omega,\mathcal F)\longrightarrow
(\mathbb R^n,\mathcal B(\mathbb R^n)).
$$

二者的联系来自分布测度。若 $h:\mathbb R^n\to\mathbb R$ 可测且相应积分存在，则变量代换公式给出

$$
\int_\Omega h(f_1,\ldots,f_n)\,dP
=\int_{\mathbb R^n}h(x_1,\ldots,x_n)\,d(P\circ f^{-1}).
$$

因此，随机向量的可测性、积分、联合分布、边缘分布与密度，都可以在有限乘积空间的框架下统一讨论。本章先保存从原第 13 章拆出的相关内容，后续再作系统整理。

# 随机向量

在 [乘积空间上的测度](13-finite-product-spaces.qmd#13-finite-product-spaces-乘积空间上的测度) 中我们提到, 乘积测度空间上的很多内容我们不需要过多讨论 (比如定义积分), 其本质上和前面定义的内容是兼容的.但是, 对于随机向量这是不兼容的, 我们需要重新构建这方面的内容.

## 定义和可测性

::: {#def-13-finite-product-spaces-30}

## 随机向量

对于概率测度空间 $(\Omega,\mathcal{F}),P$, 我们定义可测映射

$$
f:(\Omega,\mathcal{F}) \to (\mathbb{R}^{n},\mathcal{B}^{n})
$$

为**随机向量**. 此外, 令

$$
f_{k}=f\circ\pi_{k},\quad k=1,\dots,n,
$$

其中 $\pi_{k}$ 是 $\mathbb{R}^{n}$ 到第 $k$ 个 $\mathbb{R}$ 的投影, 则称 $f_{k}$ 是 $f$ 的第 $k$ 个**分量**. 容易证明, $f=(f_{1},\dots,f_{k})$.

:::
利用[投影的性质](13-finite-product-spaces.qmd#prp-project)，容易证明

::: {#thm-vector-measurable}

## 值域为乘积空间的映射的可测性判定

设 $(\Omega,\mathcal{T})$ 和 $\{ (X_{k},\mathcal{F}_{k}),k=1,\dots,n \}$ 是可测空间，$f=(f_{1},\dots,f_{n})$ 是 $\Omega$ 到 $\prod\limits_{k=1}^{n}X_{k}$ 的一个映射。则 $f$ 是 $(\Omega,\mathcal{T})$ 到 $\left( \prod\limits_{k=1}^{n}X_{k},\prod\limits_{k=1}^{n}\mathcal{F}_{k} \right)$ 的可测映射**当且仅当**对于每个 $k=1,\dots,n$，$f_{k}$ 是 $(\Omega,\mathcal{T})$ 到 $(X_{k},\mathcal{F}_{k})$ 的可测映射。

并且有这样的关系（该关系不依赖于可测性）：

$$
\sigma(f)=\sigma((f_{1},\dots,f_{n}))=\sigma\left( \bigcup_{i=1}^{n}\sigma(f_{i}) \right),
$$

如果用 $X$ 表示随机变量，则是

$$
\sigma(X_{1},\dots,X_{n})=\sigma\left( \bigcup_{i=1}^{n}\sigma(X_{i}) \right).
$$

:::

::: {.proof}

$$
\begin{align}
f^{-1}\left( \prod\limits_{k=1}^{n}\mathcal{F}_{k} \right)
&=f^{-1}\sigma\left( \bigcup_{k=1}^{n}\pi_{k}^{-1}\mathcal{F}_{k} \right) \\
&=\sigma\left( f^{-1}\left( \bigcup_{k=1}^{n}\pi_{k}^{-1}\mathcal{F}_{k} \right) \right) \\
&=\sigma\left( \bigcup_{k=1}^{n}f^{-1}(\pi_{k}^{-1}\mathcal{F}_{k}) \right) \\
&=\sigma\left( \bigcup_{k=1}^{n}(\pi_{k}\circ f)^{-1}\mathcal{F}_{k} \right)\\
&=\sigma\left( \bigcup_{k=1}^{n}f_{k}^{-1}\mathcal{F}_{k} \right).
\end{align}
$$

由上述关系可以知道，若 $f_{i}$ 可测，则 $f$ 可测。

反过来，若 $f$ 是可测映射，由于投影可测，再结合[复合映射的可测性](07-measurable-functions.qmd#thm-composite-func)，可知所有 $f_i$ 都可测。

证毕.
:::

换句话说, **$f=(f_{1},\dots,f_{n})$ 是 $n$ 维随机向量当且仅当 $f_{k},k=1,\dots,n$ 都是随机变量**。

## 随机向量生成的 $\sigma$ 代数

有时候，我们会关注随机向量生成的 $\sigma$ 代数，这里我们进行更加细致地讨论。根据 @thm-vector-measurable，我们知道

$$
\sigma(X_{1},\dots,X_{n})=\sigma\left( \bigcup_{i=1}^{n}\sigma(X_{i}) \right).
$$

所以，有时候我们需要证明某个集合系 $\mathcal{G}$ 是 $\sigma(X_{1},\dots,X_{n})$，只需要证明两点就可以：

1. $\mathcal{G}\supset\bigcup_{i=1}^{n}\sigma(X_{i})$；
2. $\mathcal{G}$ 是一个 $\sigma$ 代数。

但是有时候，以上两点不是特别容易用，所以我们有如下几个命题。

::: {#thm-multi-sigma-generate-1}

## 递归生成 $\sigma$ 代数

$$
\sigma(X_{1},\dots,X_{n})=\sigma((X_{1},\dots,X_{n-1}),X_{n})
=\sigma(\sigma(X_{1},\dots,X_{n-1})\cup\sigma(X_{n}))
 $$

:::

::: {.proof}
因为 $\sigma(X_{i})\subset\sigma(X_{1},\dots,X_{n-1}),\forall i\leq n-1$，所以有

$$
\sigma(X_{1},\dots,X_{n})\subset\sigma((X_{1},\dots,X_{n-1}),X_{n}).
$$

又因为 $\sigma(X_{1},\dots,X_{n-1})\subset\sigma(X_{1},\dots,X_{n})$ 和 $\sigma(X_{n})\subset\sigma(X_{1},\dots,X_{n})$，所以有

$$
\sigma((X_{1},\dots,X_{n-1}),X_{n})\subset\sigma(X_{1},\dots,X_{n}).
$$

:::

::: {#thm-multi-sigma-generate-2}

## $\pi$ 系生成 $\sigma$ 代数

令 $\mathcal{G}=\{ A_{1}\cap A_{2} |A_{1}\in\sigma(X_{1}),A_{2}\in\sigma(X_{2})\}$，则有

$$
\sigma(\mathcal{G})=\sigma(X_{1},X_{2}).
$$

:::

::: {.proof}
显然 $\sigma(\mathcal{G})\subset\sigma(X_{1},X_{2})$，现在我们来证明反方向。

令 $A_{2}=\Omega$，则可知

$$
\sigma(X_{1})\subset\sigma(\mathcal{G}),
$$

令 $A_{1}=\Omega$，则可知

$$
\sigma(X_{2})\subset\sigma(\mathcal{G}),
$$

因此有 $\sigma(\mathcal{G})\subset\sigma(X_{1},X_{2})$。问题得证。
:::

## 积分

注意到 [8_积分](08-integration.qmd) 中定义的积分本质上是函数值的权重和, 但对于随机向量, 函数值是一个向量, 因此相应的积分结果也应该是向量. 这里, 我们直接给出随机向量积分的定义.

::: {#def-vector-integrate}

## 随机向量的积分

对于随机向量 $f=(f_{1},\dots,f_{n})$, 其积分被定义为

$$
\int f =\left( \int f_{1},\dots,\int f_{n} \right).
$$

当位于概率测度空间中时, 积分也被称为期望, 表示为

$$
\mathbb{E}f=(\mathbb{E}f_{1},\dots,\mathbb{E}f_{n}).
$$

:::

这样的推广是合理的, 相当于我们在积分定义时将**其中所用到的标量加法和乘法**扩展至**线性空间中的向量加法和数乘**。

## 分布

在前面的学习中知道, 我们可以使用分布的概念来描述随机变量 (及测度) 所包含的信息. 分布的概念一般包含两层函数: **随机变量诱导的测度**及**分布函数**. **随机向量**也可以如此.

对于**随机向量**$f=(f_{1},\dots,f_{n})$，它是一个普通概率空间 $(X,\mathcal{F},P)\to(\mathbb{R}^{n},\mathcal{B}^{n})$ 的可测映射。其对应的诱导测度空间是 $(\mathbb{R}^{n},\mathcal{B}^{n},Pf^{-1})$, 这是一个典型的**乘积测度空间**, 因此刚才关于乘积测度空间上的内容便有了用武之地.

与 [分布函数](06-distribution-function.qmd) 中类似, 我们可以从两个方向来定义分布函数.

首先，是从**分布函数**应该满足的性质开始 (测度空间未知, 通过分布函数来生成测度)。这里直接沿用[多维分布函数](13-finite-product-spaces.qmd#def-multi-dist-func)的定义。

其次，是从**随机变量的诱导测度**出发 (定义测度相关联的分布函数):

::: {#def-n-dist-rv}

## 随机向量的分布函数

设 $f=(f_{1},\dots,f_{n})$ 是 $(X,\mathcal{F},P)$ 上的随机向量，则对每个 $(x_{1},\dots,x_{n})\in\mathbb{R}^{n}$，令

$$
F(x_{1},\dots,x_{n})=P(f_{1}\leq x_{1},\dots,f_{n}\leq x_{n}),
$$

则 $F$ 称为随机向量 $f$ 的**分布函数**，或称为 $n$ 个随机变量 $f_{1},\dots,f_{n}$ 的**联合分布函数**，记作 $f\sim F$。

:::

虽然两个定义从不同的角度出发得到, 但是两者实际上是相同的对象. 我们有如下的定理:

::: {#thm-13-finite-product-spaces-36}

## n 元分布函数对应定理（Correspondence Theorem）

(1) $n$ 维随机向量 $f$ 的分布函数是一个 $n$ 元分布函数。
(2) 任意一个给定的 $n$ 元分布函数，一定存在一个概率空间 $(X,\mathcal{F},P)$，在其上定义有随机向量 $f\sim F$。

:::
::: {.proof}
（1）由概率测度的下连续性和有界性，可以验证[多维准分布函数](13-finite-product-spaces.qmd#def-high-dim-distribution)的右连续性以及[多维分布函数](13-finite-product-spaces.qmd#def-multi-dist-func)的边界条件。因此，只需再证明 **n 重差分非负性**。

为了证明这个，我们可以应用 @thm-inclusion-exclusion，或者使用**差分算子**来进行讨论。下面我们使用第二种方案。

定义针对第 $i$ 个坐标的差分算子 $\Delta_i$ 为：

$$
 \Delta_{a_i, b_i} F(x_1, \dots, x_n) = F(x_1, \dots, b_i, \dots, x_n) - F(x_1, \dots, a_i, \dots, x_n)
$$

这其实就是 $P(X \in \dots \times (a_i, b_i] \times \dots)$，只考虑第 $i$ 个维度的限制。现在，我们考虑 $n$ 维矩形

$$
R = (a_1, b_1] \times \dots \times (a_n, b_n].
$$

随机向量 $X$ 落在 $R$ 中的事件，就是所有分量 $X_i$ 都落在 $(a_i, b_i]$ 中。这就相当于对分布函数 $F$ 在所有 $n$ 个维度上依次做差分：

$$
\begin{aligned}
P(a < X \le b) &= P(a_1 < X_1 \le b_1, \dots, a_n < X_n \le b_n) \\
&= \Delta_{a_n, b_n} \left( \dots \left( \Delta_{a_1, b_1} F(x_1, \dots, x_n) \right) \dots \right)
\end{aligned}
$$

**让我们展开这个差分运算。** 每个算子 $\Delta_{a_i, b_i}$ 都是两项之差：(代入 $b_i$) - (代入 $a_i$)。如果你把 $n$ 个这样的算子乘起来（即连续作用）, 就会得到

$$
 \prod_{i=1}^n (\text{代入 } b_i - \text{代入 } a_i)
$$

展开这个括号，你会得到 $2^n$ 项。每一项都是 $F$ 在某个点 $c$ 的值，其中 $c$ 的第 $i$ 个分量要么是 $b_i$，要么是 $a_i$。
* 如果选择了“代入 $b_i$”，该项系数贡献一个正号 $(+1)$。
* 如果选择了“代入 $a_i$”，该项系数贡献一个负号 $(-1)$。

因此，对于任意一个顶点 $c$，如果它有 $k$ 个分量取自 $a$（即 $n(c)=k$），那么它的总符号就是 $k$ 个 $(-1)$ 相乘，即 $(-1)^k$。这就推导出了定义中的公式：

$$
 P(a < X \le b) = \sum_{c \in C} (-1)^{n(c)} F(c)
$$

而根据概率测度的非负性，可知上面这个式子是 $\geq 0$ 的。

（2）利用[矩形增量定义的预测度](13-finite-product-spaces.qmd#prp-n-dist-semi-ring-measure)，可以先在半开矩形半环上定义测度，再利用[测度扩张定理](05-measure-extension.qmd#thm-measure-extension)得到唯一扩张。容易验证所得概率测度满足 @def-n-dist-rv 中的公式。

:::

因为**随机向量可以表示为多个随机变量的组合**, 那么自然的一个问题是: 这些**随机变量的分布**与**随机向量的分布**之间是否存在联系? 为了能够去探讨这个问题, 我们需要先定义**边缘分布** (也就是分量的分布).

::: {#def-margin-dist}

## 边缘分布函数

设 $f=(f_{1},\dots,f_{n})$ 是 $(X,\mathcal{F},P)$ 上的随机向量，对任意给定的指标 $i_{1},\dots,i_{k},k\leq n$，则称 $(f_{i_{1}},\dots,f_{i_{k}})$ 的联合分布函数叫做 **$f$ 的第 $i_{1},\dots,i_{k}$ 个分量的边缘分布函数**。特别的，第 $i$ 个分量 $f_{i}$ 的边缘分布函数记作 $F_{i}$（$=Pf_{i}^{-1}((-\infty,x])$）。

:::

结合 [多维 L-S 测度](13-finite-product-spaces.qmd#13-finite-product-spaces-多维-l-s-测度) 中的讨论可以知道, 正常情况下使用 $\{ F_{i},i=1,\dots,n \}$ 是无法确定 $F$ 的，除非是在**独立**这一特殊的条件下，这个将在[独立性的分布刻画](16-independence-and-conditional-expectation.qmd#thm-indepent-distribution)中讨论。

::: {.callout-note}
这里有一个非常容易混淆的点。**一维测度的乘积来确定高维测度**这样的内容在本章的内容中出现了两次：
- 通过一维测度空间中的测度来生成高维测度空间中的测度；
- 通过边缘分布来确定联合分布。

这提示两者之间存在联系：根据[独立性的分布刻画](16-independence-and-conditional-expectation.qmd#thm-indepent-distribution)，当**独立性成立**时，联合分布恰好等于边缘分布的乘积。

:::

::: {#thm-inclusion-exclusion}

## 容斥原理

（集合论形式）设 $A_1, A_2, \dots, A_n$ 为有限集合，则这 $n$ 个集合的并集的元素个数为：

$$
\left| \bigcup_{i=1}^n A_i \right| = \sum_{1 \le i \le n} |A_i| - \sum_{1 \le i < j \le n} |A_i \cap A_j| + \sum_{1 \le i < j < k \le n} |A_i \cap A_j \cap A_k| - \dots + (-1)^{n-1} |A_1 \cap \dots \cap A_n|
$$

（概率论形式）设 $(\Omega, \mathcal{F}, P)$ 为概率空间，$A_1, A_2, \dots, A_n \in \mathcal{F}$ 为一系列事件。则这些事件中至少有一个发生的概率（即并集的概率）为：

$$
P\left( \bigcup_{i=1}^n A_i \right) = \sum_{1 \le i \le n} P(A_i) - \sum_{1 \le i < j \le n} P(A_i \cap A_j) + \dots + (-1)^{n-1} P\left( \bigcap_{i=1}^n A_i \right)
$$
:::

## 密度

仿照一维情形，可以直接应用 [Radon–Nikodym 定理](11-radon-nikodym-derivative.qmd#thm-rn)定义高维密度。假设对随机向量 $f=(f_1,\ldots,f_n)$，存在 $(\mathbb R^n,\mathcal B^n)$ 上的 $\sigma$ 有限测度 $\mu$ 使

$$
Pf^{-1}\ll \mu.
$$

此时，由 [Radon–Nikodym 定理](11-radon-nikodym-derivative.qmd#thm-rn)存在可测函数 $\frac{dPf^{-1}}{d\mu}: (\mathbb{R}^{n},\mathcal{B}^{n})\to(\mathbb{R},\mathcal{B})$，满足

$$
\int _{A}\frac{dPf^{-1}}{d\mu} \, d\mu=Pf^{-1}(A)=P(f\in A),\quad
\forall A\in\mathcal{B^{n}}.
$$

可测函数 $\frac{dPf^{-1}}{d\mu}$ 被称为 **$f$ 相对于 $\mu$ 的密度函数**，可见，**其是一个输入 $n$ 个值，输出 1 个值的函数**。当然, 我们也可以去定义**单个随机变量的边缘概率密度**, 也就是其**边缘分布的 R-N 导数**。相关导数规则见 [Radon–Nikodym 导数的性质](11-radon-nikodym-derivative.qmd#prp-rn)。

下面, 我们将证明下面的一个推论, 其描述了**联合概率密度**和**边缘概率密度**之间的关系.

::: {#prp-comb-margin-density}

## 联合密度和边缘密度

若 $p(x,y)$ 是 $n$ 和 $m$ 维随机向量 $X,Y$ 相对于 $\lambda \times \mu$ 的联合概率密度函数, 则有

$$
\int p(x,y) \, \lambda(dx)=\frac{PY^{-1}(dy)}{\mu(dy)}\ a.s.,
$$

和

$$
\int p(x,y) \, \mu(dy)=\frac{PX^{-1}(dx)}{\lambda(dx)}\ a.s..
$$

此外, 该结论可以推广至有限维联合概率密度.

:::

::: {.proof}
$\forall B\in\mathcal{B}^{m}$，利用 [Radon–Nikodym 导数的性质](11-radon-nikodym-derivative.qmd#prp-rn) 有

$$
\begin{align}
PY^{-1}(B)=\int _{B} PY^{-1}(dy)
=\int _{B}\frac{PY^{-1}(dy)}{\mu(dy)} \, \mu(dy),
\end{align}
$$

此外, 我们还有

$$
\begin{align}
PY^{-1}(B)&=P(X,Y)^{-1}(\mathbb{R}^{n}\times B) \\
&=
\int _{\mathbb{R}^{n}\times B}p(x,y) \, (\lambda \times \mu)(dxdy) \\
&=\int _{B}\mu(dy)\int _{\mathbb{R}^{n}}f(x,y)\lambda(dx),
\end{align}
$$

其中最后一行使用了 [Fubini 定理](13-finite-product-spaces.qmd#thm-fubini)。联立两个等式，得到

$$
\int p(x,y) \, \lambda(dx)=\frac{PY^{-1}(dy)}{\mu(dy)}\ a.s..
$$

使用类似的方法可以得到另外一个等式的结果.
:::
